// Mock data for development / demo when no Supabase is configured

const now = Date.now()

export const MOCK_POSTS = [
  {
    id: 'mock-1',
    user_id: 'user-1',
    mode: 'realtime',
    category: 'fashion',
    question: 'Which outfit for tonight?',
    status: 'active',
    expires_at: new Date(now + 8 * 60 * 1000).toISOString(),
    created_at: new Date(now - 7 * 60 * 1000).toISOString(),
    users: { username: 'sophiaa', avatar_url: null },
    options: [
      { id: 'opt-1a', post_id: 'mock-1', label: 'Option A', photo_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&q=80', vote_count: 34 },
      { id: 'opt-1b', post_id: 'mock-1', label: 'Option B', photo_url: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400&q=80', vote_count: 12 },
    ],
    ai_verdicts: [{ recommendation_option_id: 'opt-1a', insights: [{ text: 'More versatile for evening events' }] }],
    vote_total: 46,
  },
  {
    id: 'mock-2',
    user_id: 'user-2',
    mode: 'realtime',
    category: 'food',
    question: 'Which dessert looks more appealing?',
    status: 'active',
    expires_at: new Date(now + 3 * 60 * 1000).toISOString(),
    created_at: new Date(now - 12 * 60 * 1000).toISOString(),
    users: { username: 'marcofood', avatar_url: null },
    options: [
      { id: 'opt-2a', post_id: 'mock-2', label: 'Option A', photo_url: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400&q=80', vote_count: 21 },
      { id: 'opt-2b', post_id: 'mock-2', label: 'Option B', photo_url: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&q=80', vote_count: 29 },
    ],
    ai_verdicts: [{ recommendation_option_id: 'opt-2b', insights: [{ text: 'Richer visual contrast and texture' }] }],
    vote_total: 50,
  },
  {
    id: 'mock-3',
    user_id: 'user-3',
    mode: 'twelve_hour',
    category: 'home',
    question: 'Which sofa fits better in a modern living room?',
    status: 'active',
    expires_at: new Date(now + 6 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(now - 6 * 60 * 60 * 1000).toISOString(),
    users: { username: 'interior_jen', avatar_url: null },
    options: [
      { id: 'opt-3a', post_id: 'mock-3', label: 'Option A', photo_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80', vote_count: 67 },
      { id: 'opt-3b', post_id: 'mock-3', label: 'Option B', photo_url: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=400&q=80', vote_count: 43 },
    ],
    ai_verdicts: [{ recommendation_option_id: 'opt-3a', insights: [{ text: 'Clean lines suit minimalist spaces' }] }],
    vote_total: 110,
  },
  {
    id: 'mock-4',
    user_id: 'user-4',
    mode: 'twelve_hour',
    category: 'design',
    question: 'Which logo concept should we go with?',
    status: 'active',
    expires_at: new Date(now + 9 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(now - 3 * 60 * 60 * 1000).toISOString(),
    users: { username: 'designluke', avatar_url: null },
    options: [
      { id: 'opt-4a', post_id: 'mock-4', label: 'Option A', photo_url: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&q=80', vote_count: 88 },
      { id: 'opt-4b', post_id: 'mock-4', label: 'Option B', photo_url: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&q=80', vote_count: 55 },
      { id: 'opt-4c', post_id: 'mock-4', label: 'Option C', photo_url: 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=400&q=80', vote_count: 30 },
    ],
    ai_verdicts: [{ recommendation_option_id: 'opt-4a', insights: [{ text: 'Higher brand recall score in studies' }] }],
    vote_total: 173,
  },
  {
    id: 'mock-5',
    user_id: 'user-5',
    mode: 'realtime',
    category: 'beauty',
    question: 'Red or nude lip for the event?',
    status: 'active',
    expires_at: new Date(now + 1 * 60 * 1000).toISOString(),
    created_at: new Date(now - 14 * 60 * 1000).toISOString(),
    users: { username: 'glam.rosa', avatar_url: null },
    options: [
      { id: 'opt-5a', post_id: 'mock-5', label: 'Option A', photo_url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&q=80', vote_count: 104 },
      { id: 'opt-5b', post_id: 'mock-5', label: 'Option B', photo_url: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&q=80', vote_count: 78 },
    ],
    ai_verdicts: [{ recommendation_option_id: 'opt-5a', insights: [{ text: 'Makes a stronger impression for evening' }] }],
    vote_total: 182,
  },
]
